class CreateBarrios < ActiveRecord::Migration[6.0]
  def change
    create_table :barrios do |t|
      t.references :localidad, null: false, foreign_key: true
      t.string :nombre

      t.timestamps
    end

    Barrio.create(:id=>1, :localidad_id=>1, :nombre=>'54 VIVIENDAS')
	Barrio.create(:id=>2, :localidad_id=>1, :nombre=>'C. COLORADO 138 VIV.')
	Barrio.create(:id=>3, :localidad_id=>1, :nombre=>'C.COLORADO  57 VIV')
	Barrio.create(:id=>4, :localidad_id=>1, :nombre=>'C.COLORADO 104 VIV')
	Barrio.create(:id=>5, :localidad_id=>1, :nombre=>'C.COLORADO 130 VIV')
	Barrio.create(:id=>6, :localidad_id=>1, :nombre=>'LOS EUCALIPTUS')
	Barrio.create(:id=>7, :localidad_id=>1, :nombre=>'LOS FRESNO')
	Barrio.create(:id=>8, :localidad_id=>1, :nombre=>'LOTEO CORRALES DE PIEDRA')
	Barrio.create(:id=>9, :localidad_id=>1, :nombre=>'PASEO VIRGEN DE FATIMA')
	Barrio.create(:id=>10, :localidad_id=>1, :nombre=>'SAN ROQUE')
	Barrio.create(:id=>11, :localidad_id=>1, :nombre=>'SIN BARRIO')
	Barrio.create(:id=>12, :localidad_id=>1, :nombre=>'SOLARES DEL GOLF')
	Barrio.create(:id=>13, :localidad_id=>2, :nombre=>'CUCHI CORRAL')
	Barrio.create(:id=>14, :localidad_id=>2, :nombre=>'LOTEO CUESTA DE PIEDRA')
	Barrio.create(:id=>15, :localidad_id=>2, :nombre=>'LOTEO LOS ALMENDROS')
	Barrio.create(:id=>16, :localidad_id=>2, :nombre=>'SIN BARRIO')
	Barrio.create(:id=>17, :localidad_id=>3, :nombre=>'25 VIVIENDAS PLAN SOLIDARIDAD')
	Barrio.create(:id=>18, :localidad_id=>3, :nombre=>'CHACRAS DE DONOVAN (3 LOMAS)')
	Barrio.create(:id=>19, :localidad_id=>3, :nombre=>'LOTEO ZARATE')
	Barrio.create(:id=>20, :localidad_id=>3, :nombre=>'PLAN DE INCLUSION')
	Barrio.create(:id=>21, :localidad_id=>3, :nombre=>'SIN BARRIO')
	Barrio.create(:id=>22, :localidad_id=>4, :nombre=>'274 VIVIENDAS')
	Barrio.create(:id=>23, :localidad_id=>4, :nombre=>'CAMPOCHICO')
	Barrio.create(:id=>24, :localidad_id=>4, :nombre=>'EL CAMPESTRE')
	Barrio.create(:id=>25, :localidad_id=>4, :nombre=>'ESC. BERTIN  57 VIV')
	Barrio.create(:id=>26, :localidad_id=>4, :nombre=>'ESC. JORGE S. BERTIN')
	Barrio.create(:id=>27, :localidad_id=>4, :nombre=>'FRANCISCO OYOLA')
	Barrio.create(:id=>28, :localidad_id=>4, :nombre=>'GREGORIO VIVAS  57 VIV')
	Barrio.create(:id=>29, :localidad_id=>4, :nombre=>'GREGORIO VIVAS -71 VIV.')
	Barrio.create(:id=>30, :localidad_id=>4, :nombre=>'JUAN G. VIVAS')
	Barrio.create(:id=>31, :localidad_id=>4, :nombre=>'LA CAÑADA')
	Barrio.create(:id=>32, :localidad_id=>4, :nombre=>'LA JOAQUINA')
	Barrio.create(:id=>33, :localidad_id=>4, :nombre=>'LA JOAQUINA OPEN MALL')
	Barrio.create(:id=>34, :localidad_id=>4, :nombre=>'LAS ACASIAS')
	Barrio.create(:id=>35, :localidad_id=>4, :nombre=>'LAS PALMERAS')
	Barrio.create(:id=>36, :localidad_id=>4, :nombre=>'LOMAS DE LA AGUADA')
	Barrio.create(:id=>37, :localidad_id=>4, :nombre=>'LOS NOGALES')
	Barrio.create(:id=>38, :localidad_id=>4, :nombre=>'LOTEO EL PORTEZUELO')
	Barrio.create(:id=>39, :localidad_id=>4, :nombre=>'LOTEO FUNCIA')
	Barrio.create(:id=>40, :localidad_id=>4, :nombre=>'LOTEO LOS OLIVOS')
	Barrio.create(:id=>41, :localidad_id=>4, :nombre=>'LOTEO SANTA ISABEL')
	Barrio.create(:id=>42, :localidad_id=>4, :nombre=>'NUESTRA MADRE DE SCHOENSTATT')
	Barrio.create(:id=>43, :localidad_id=>4, :nombre=>'SIN BARRIO')
	Barrio.create(:id=>44, :localidad_id=>4, :nombre=>'Sin Barrio1')
	Barrio.create(:id=>45, :localidad_id=>4, :nombre=>'UPCN')
	Barrio.create(:id=>46, :localidad_id=>5, :nombre=>'SIN BARRIO')
	Barrio.create(:id=>47, :localidad_id=>6, :nombre=>'SIN BARRIO')
	Barrio.create(:id=>48, :localidad_id=>7, :nombre=>'SIN BARRIO')
	Barrio.create(:id=>49, :localidad_id=>8, :nombre=>'SIN BARRIO')
	Barrio.create(:id=>50, :localidad_id=>9, :nombre=>'APART DE LAGO')
	Barrio.create(:id=>51, :localidad_id=>9, :nombre=>'BARRIO LA PANCHA')
	Barrio.create(:id=>52, :localidad_id=>9, :nombre=>'BARRIO LA PANCHA 2')
	Barrio.create(:id=>53, :localidad_id=>9, :nombre=>'BARRIO LA PANCHA 3')
	Barrio.create(:id=>54, :localidad_id=>9, :nombre=>'LOS NARANJOS')
	Barrio.create(:id=>55, :localidad_id=>9, :nombre=>'LOTEO LA BALDOMERA')
	Barrio.create(:id=>56, :localidad_id=>9, :nombre=>'LOTEO LAS PRADERAS')
	Barrio.create(:id=>57, :localidad_id=>9, :nombre=>'LOTEO LOS LECHUZOS')
	Barrio.create(:id=>58, :localidad_id=>9, :nombre=>'LOTEO MANQUEHUE')
	Barrio.create(:id=>59, :localidad_id=>9, :nombre=>'LOTEO MEDERO MARIA FERNANDA')
	Barrio.create(:id=>60, :localidad_id=>9, :nombre=>'LOTEO PASO DEL LIBERTADOR')
	Barrio.create(:id=>61, :localidad_id=>9, :nombre=>'NORTE')
	Barrio.create(:id=>62, :localidad_id=>9, :nombre=>'PUEBLO SERRANO PAMPAZUL')
	Barrio.create(:id=>63, :localidad_id=>9, :nombre=>'SIN BARRIO')
	Barrio.create(:id=>64, :localidad_id=>9, :nombre=>'VALLE ESCONDIDO')
	Barrio.create(:id=>65, :localidad_id=>9, :nombre=>'VILLA ANTONIO')
	Barrio.create(:id=>66, :localidad_id=>9, :nombre=>'VILLA ANTONIO 2')
	Barrio.create(:id=>67, :localidad_id=>10, :nombre=>'274 VIVIENDAS')
	Barrio.create(:id=>68, :localidad_id=>10, :nombre=>'LOTEO BARRANCAS DE J.KOSLAY')
	Barrio.create(:id=>69, :localidad_id=>10, :nombre=>'LOTEO LA AGRIPINA')
	Barrio.create(:id=>70, :localidad_id=>10, :nombre=>'SIN BARRIO')
	Barrio.create(:id=>71, :localidad_id=>11, :nombre=>'SIN BARRIO')
	Barrio.create(:id=>72, :localidad_id=>12, :nombre=>'ALTOS DE LOS PUQUIOS I')
	Barrio.create(:id=>73, :localidad_id=>12, :nombre=>'BRUCEN')
	Barrio.create(:id=>74, :localidad_id=>12, :nombre=>'DUPUY')
	Barrio.create(:id=>75, :localidad_id=>12, :nombre=>'LAS CATALPAS')
	Barrio.create(:id=>76, :localidad_id=>12, :nombre=>'LOTEO ALTOS DE LOS PUQUIOS')
	Barrio.create(:id=>77, :localidad_id=>12, :nombre=>'PARQUE IND. S.ROQUE')
	Barrio.create(:id=>78, :localidad_id=>12, :nombre=>'SIN BARRIO')


  end
end
