class CreateCalles < ActiveRecord::Migration[6.0]
  def change
    create_table :calles do |t|
      t.references :barrio, null: false, foreign_key: true
      t.string :nombre

      t.timestamps
    end

	Calle.create(:id=>1, :barrio_id=>1, :nombre=>'MANZANA 11')
	Calle.create(:id=>2, :barrio_id=>1, :nombre=>'MANZANA 36')
	Calle.create(:id=>3, :barrio_id=>1, :nombre=>'MANZANA 37')
	Calle.create(:id=>4, :barrio_id=>1, :nombre=>'MANZANA 40')
	Calle.create(:id=>5, :barrio_id=>1, :nombre=>'MANZANA 43')
	Calle.create(:id=>6, :barrio_id=>1, :nombre=>'MANZANA 45')
	Calle.create(:id=>7, :barrio_id=>1, :nombre=>'MANZANA 46')
	Calle.create(:id=>8, :barrio_id=>2, :nombre=>'MANZANA 34')
	Calle.create(:id=>9, :barrio_id=>2, :nombre=>'MANZANA 35')
	Calle.create(:id=>10, :barrio_id=>2, :nombre=>'MANZANA 36')
	Calle.create(:id=>11, :barrio_id=>2, :nombre=>'MANZANA 37')
	Calle.create(:id=>12, :barrio_id=>2, :nombre=>'MANZANA 39')
	Calle.create(:id=>13, :barrio_id=>2, :nombre=>'MANZANA 40')
	Calle.create(:id=>14, :barrio_id=>2, :nombre=>'MANZANA 41')
	Calle.create(:id=>15, :barrio_id=>3, :nombre=>'MANZANA A')
	Calle.create(:id=>16, :barrio_id=>3, :nombre=>'MANZANA B')
	Calle.create(:id=>17, :barrio_id=>4, :nombre=>'MANZANA 26')
	Calle.create(:id=>18, :barrio_id=>4, :nombre=>'MANZANA 27')
	Calle.create(:id=>19, :barrio_id=>4, :nombre=>'MANZANA 29')
	Calle.create(:id=>20, :barrio_id=>4, :nombre=>'MANZANA 32')
	Calle.create(:id=>21, :barrio_id=>4, :nombre=>'MANZANA 33')
	Calle.create(:id=>22, :barrio_id=>5, :nombre=>'MANZANA 16')
	Calle.create(:id=>23, :barrio_id=>5, :nombre=>'MANZANA 17')
	Calle.create(:id=>24, :barrio_id=>5, :nombre=>'MANZANA 18')
	Calle.create(:id=>25, :barrio_id=>5, :nombre=>'MANZANA 19')
	Calle.create(:id=>26, :barrio_id=>5, :nombre=>'MANZANA 23')
	Calle.create(:id=>27, :barrio_id=>5, :nombre=>'MANZANA 24')
	Calle.create(:id=>28, :barrio_id=>5, :nombre=>'MANZANA 28')
	Calle.create(:id=>29, :barrio_id=>5, :nombre=>'MANZANA 30')
	Calle.create(:id=>30, :barrio_id=>5, :nombre=>'MANZANA 31')
	Calle.create(:id=>31, :barrio_id=>6, :nombre=>'AV. LOS EUCALIPTUS')
	Calle.create(:id=>32, :barrio_id=>6, :nombre=>'MANZANA 18')
	Calle.create(:id=>33, :barrio_id=>6, :nombre=>'MANZANA 19')
	Calle.create(:id=>34, :barrio_id=>6, :nombre=>'MANZANA 20')
	Calle.create(:id=>35, :barrio_id=>6, :nombre=>'MANZANA 21')
	Calle.create(:id=>36, :barrio_id=>6, :nombre=>'MANZANA 22')
	Calle.create(:id=>37, :barrio_id=>6, :nombre=>'MANZANA 23')
	Calle.create(:id=>38, :barrio_id=>6, :nombre=>'MANZANA 24')
	Calle.create(:id=>39, :barrio_id=>6, :nombre=>'MANZANA 25')
	Calle.create(:id=>40, :barrio_id=>6, :nombre=>'MANZANA 26')
	Calle.create(:id=>41, :barrio_id=>6, :nombre=>'MANZANA 27')
	Calle.create(:id=>42, :barrio_id=>6, :nombre=>'MANZANA 28')
	Calle.create(:id=>43, :barrio_id=>6, :nombre=>'MANZANA 29')
	Calle.create(:id=>44, :barrio_id=>6, :nombre=>'MANZANA 30')
	Calle.create(:id=>45, :barrio_id=>6, :nombre=>'MANZANA 31')
	Calle.create(:id=>46, :barrio_id=>6, :nombre=>'MANZANA 32')
	Calle.create(:id=>47, :barrio_id=>6, :nombre=>'MANZANA 33')
	Calle.create(:id=>48, :barrio_id=>6, :nombre=>'MANZANA 34')
	Calle.create(:id=>49, :barrio_id=>6, :nombre=>'MANZANA 35')
	Calle.create(:id=>50, :barrio_id=>6, :nombre=>'MANZANA 36')
	Calle.create(:id=>51, :barrio_id=>6, :nombre=>'MANZANA 37')
	Calle.create(:id=>52, :barrio_id=>6, :nombre=>'MANZANA 39')
	Calle.create(:id=>53, :barrio_id=>7, :nombre=>'MANZANA 7')
	Calle.create(:id=>54, :barrio_id=>7, :nombre=>'MANZANA 8')
	Calle.create(:id=>55, :barrio_id=>8, :nombre=>'PARCELA')
	Calle.create(:id=>56, :barrio_id=>9, :nombre=>'MANZANA 40')
	Calle.create(:id=>57, :barrio_id=>9, :nombre=>'MANZANA 41')
	Calle.create(:id=>58, :barrio_id=>10, :nombre=>'LAS JARILLAS')
	Calle.create(:id=>59, :barrio_id=>11, :nombre=>'AV. CRUZ DE PIEDRA')
	Calle.create(:id=>60, :barrio_id=>11, :nombre=>'AV. LAS CHACRAS')
	Calle.create(:id=>61, :barrio_id=>11, :nombre=>'AV. PRESIDENTE PERON')
	Calle.create(:id=>62, :barrio_id=>11, :nombre=>'CALLE PUBLICA')
	Calle.create(:id=>63, :barrio_id=>11, :nombre=>'CRUZ DE PIEDRA')
	Calle.create(:id=>64, :barrio_id=>11, :nombre=>'CUESTA DEL GATO')
	Calle.create(:id=>65, :barrio_id=>11, :nombre=>'DOLORES ROSALES')
	Calle.create(:id=>66, :barrio_id=>11, :nombre=>'EL ALGARROBO ABUELO')
	Calle.create(:id=>67, :barrio_id=>11, :nombre=>'LA CAROLINA')
	Calle.create(:id=>68, :barrio_id=>11, :nombre=>'LAS HIEDRAS')
	Calle.create(:id=>69, :barrio_id=>11, :nombre=>'LOS ELYOTIS')
	Calle.create(:id=>70, :barrio_id=>11, :nombre=>'MULTITROCHA')
	Calle.create(:id=>71, :barrio_id=>11, :nombre=>'PASAJE CUESTA DEL GATO')
	Calle.create(:id=>72, :barrio_id=>11, :nombre=>'PASO DEL REY')
	Calle.create(:id=>73, :barrio_id=>11, :nombre=>'PUNTANITO')
	Calle.create(:id=>74, :barrio_id=>11, :nombre=>'RUTA 20')
	Calle.create(:id=>75, :barrio_id=>12, :nombre=>'BLOCK 1')
	Calle.create(:id=>76, :barrio_id=>12, :nombre=>'BLOCK 2')
	Calle.create(:id=>77, :barrio_id=>12, :nombre=>'BLOCK 3')
	Calle.create(:id=>78, :barrio_id=>12, :nombre=>'BLOCK 4')
	Calle.create(:id=>79, :barrio_id=>12, :nombre=>'BLOCK 6')
	Calle.create(:id=>80, :barrio_id=>12, :nombre=>'BLOCK 8')
	Calle.create(:id=>81, :barrio_id=>13, :nombre=>'MULTITROCHA')
	Calle.create(:id=>82, :barrio_id=>14, :nombre=>'AV. CUCHI CORRAL')
	Calle.create(:id=>83, :barrio_id=>15, :nombre=>'AV. CUCHI CORRAL')
	Calle.create(:id=>84, :barrio_id=>16, :nombre=>'CUCHI CORRAL')
	Calle.create(:id=>85, :barrio_id=>16, :nombre=>'ENLACE CUCHI CORRAL RUTA 7')
	Calle.create(:id=>86, :barrio_id=>16, :nombre=>'MULTITROCHA')
	Calle.create(:id=>87, :barrio_id=>16, :nombre=>'PASAJE DOLORES ROSALES')
	Calle.create(:id=>88, :barrio_id=>16, :nombre=>'PSJE CAMINO VERDE')
	Calle.create(:id=>89, :barrio_id=>16, :nombre=>'RUTA 7')
	Calle.create(:id=>90, :barrio_id=>17, :nombre=>'CASA')
	Calle.create(:id=>91, :barrio_id=>17, :nombre=>'PARCELA')
	Calle.create(:id=>92, :barrio_id=>18, :nombre=>'MANZANA 35')
	Calle.create(:id=>93, :barrio_id=>18, :nombre=>'MANZANA 36')
	Calle.create(:id=>94, :barrio_id=>18, :nombre=>'MANZANA 37')
	Calle.create(:id=>95, :barrio_id=>19, :nombre=>'CALLE PUBLICA')
	Calle.create(:id=>96, :barrio_id=>20, :nombre=>'CASA')
	Calle.create(:id=>97, :barrio_id=>21, :nombre=>'CAMINO A DONOVAN')
	Calle.create(:id=>98, :barrio_id=>21, :nombre=>'DONOVAN')
	Calle.create(:id=>99, :barrio_id=>21, :nombre=>'ESTACION DONOVAN')
	Calle.create(:id=>100, :barrio_id=>22, :nombre=>'MANZANA A')
	Calle.create(:id=>101, :barrio_id=>22, :nombre=>'MANZANA D')
	Calle.create(:id=>102, :barrio_id=>23, :nombre=>'CALLE PRINCIPAL')
	Calle.create(:id=>103, :barrio_id=>24, :nombre=>'LOTE')
	Calle.create(:id=>104, :barrio_id=>25, :nombre=>'MANZANA 35')
	Calle.create(:id=>105, :barrio_id=>26, :nombre=>'MANZANA 29')
	Calle.create(:id=>106, :barrio_id=>26, :nombre=>'MANZANA 37')
	Calle.create(:id=>107, :barrio_id=>26, :nombre=>'MANZANA 38')
	Calle.create(:id=>108, :barrio_id=>26, :nombre=>'MANZANA 39')
	Calle.create(:id=>109, :barrio_id=>27, :nombre=>'MANZANA 12')
	Calle.create(:id=>110, :barrio_id=>27, :nombre=>'MANZANA 28')
	Calle.create(:id=>111, :barrio_id=>27, :nombre=>'MANZANA 29')
	Calle.create(:id=>112, :barrio_id=>27, :nombre=>'MANZANA A')
	Calle.create(:id=>113, :barrio_id=>27, :nombre=>'MANZANA B')
	Calle.create(:id=>114, :barrio_id=>27, :nombre=>'MANZANA C')
	Calle.create(:id=>115, :barrio_id=>27, :nombre=>'TERESA DE LOS ANDES')
	Calle.create(:id=>116, :barrio_id=>28, :nombre=>'MANZANA 42')
	Calle.create(:id=>117, :barrio_id=>29, :nombre=>'MANZANA 43')
	Calle.create(:id=>118, :barrio_id=>29, :nombre=>'MANZANA 45')
	Calle.create(:id=>119, :barrio_id=>29, :nombre=>'MANZANA 46')
	Calle.create(:id=>120, :barrio_id=>29, :nombre=>'MANZANA 47')
	Calle.create(:id=>121, :barrio_id=>29, :nombre=>'MANZANA 48')
	Calle.create(:id=>122, :barrio_id=>30, :nombre=>'MANZANA 10')
	Calle.create(:id=>123, :barrio_id=>30, :nombre=>'MANZANA 37')
	Calle.create(:id=>124, :barrio_id=>30, :nombre=>'MANZANA 40')
	Calle.create(:id=>125, :barrio_id=>30, :nombre=>'MANZANA 41')
	Calle.create(:id=>126, :barrio_id=>30, :nombre=>'MANZANA 43')
	Calle.create(:id=>127, :barrio_id=>30, :nombre=>'MANZANA 44')
	Calle.create(:id=>128, :barrio_id=>31, :nombre=>'ARTURO RODRIGUEZ JURADO')
	Calle.create(:id=>129, :barrio_id=>31, :nombre=>'CONCARAN SUR')
	Calle.create(:id=>130, :barrio_id=>31, :nombre=>'DON ATA')
	Calle.create(:id=>131, :barrio_id=>31, :nombre=>'JACQUEN YVES COUSTEAU')
	Calle.create(:id=>132, :barrio_id=>31, :nombre=>'MANZANA 31')
	Calle.create(:id=>133, :barrio_id=>31, :nombre=>'MANZANA 41')
	Calle.create(:id=>134, :barrio_id=>31, :nombre=>'MANZANA 42')
	Calle.create(:id=>135, :barrio_id=>31, :nombre=>'MANZANA 43')
	Calle.create(:id=>136, :barrio_id=>31, :nombre=>'MANZANA A')
	Calle.create(:id=>137, :barrio_id=>32, :nombre=>'AGUADA DE PUEYRREDON')
	Calle.create(:id=>138, :barrio_id=>32, :nombre=>'LOS NOGALES')
	Calle.create(:id=>139, :barrio_id=>32, :nombre=>'MANZANA 1')
	Calle.create(:id=>140, :barrio_id=>33, :nombre=>'LOTE')
	Calle.create(:id=>141, :barrio_id=>34, :nombre=>'CASA')
	Calle.create(:id=>142, :barrio_id=>35, :nombre=>'MANZANA 32')
	Calle.create(:id=>143, :barrio_id=>35, :nombre=>'MANZANA 33')
	Calle.create(:id=>144, :barrio_id=>35, :nombre=>'MANZANA 34')
	Calle.create(:id=>145, :barrio_id=>35, :nombre=>'MANZANA 35')
	Calle.create(:id=>146, :barrio_id=>35, :nombre=>'MANZANA 36')
	Calle.create(:id=>147, :barrio_id=>36, :nombre=>'PANCANTA')
	Calle.create(:id=>148, :barrio_id=>37, :nombre=>'MANZANA D')
	Calle.create(:id=>149, :barrio_id=>38, :nombre=>'LOTE 9')
	Calle.create(:id=>150, :barrio_id=>39, :nombre=>'MANZANA 1')
	Calle.create(:id=>151, :barrio_id=>39, :nombre=>'MANZANA 5')
	Calle.create(:id=>152, :barrio_id=>39, :nombre=>'QUEBRACHO BLANCO')
	Calle.create(:id=>153, :barrio_id=>40, :nombre=>'PASAJE LAS MARGARITAS')
	Calle.create(:id=>154, :barrio_id=>40, :nombre=>'PJE LAS MARGARITAS')
	Calle.create(:id=>155, :barrio_id=>41, :nombre=>'LOTE')
	Calle.create(:id=>156, :barrio_id=>42, :nombre=>'AGUADA DE PUEYRREDON')
	Calle.create(:id=>157, :barrio_id=>42, :nombre=>'MANZANA 32')
	Calle.create(:id=>158, :barrio_id=>42, :nombre=>'MANZANA 34')
	Calle.create(:id=>159, :barrio_id=>42, :nombre=>'MANZANA 37')
	Calle.create(:id=>160, :barrio_id=>43, :nombre=>'1 DE MAYO')
	Calle.create(:id=>161, :barrio_id=>43, :nombre=>'18 DE FEBRERO')
	Calle.create(:id=>162, :barrio_id=>43, :nombre=>'20 DE NOVIEMBRE')
	Calle.create(:id=>163, :barrio_id=>43, :nombre=>'28 DE FEBRERO')
	Calle.create(:id=>164, :barrio_id=>43, :nombre=>'AGUADA DE LOS PADRES')
	Calle.create(:id=>165, :barrio_id=>43, :nombre=>'AGUADA DE PUEYRREDON')
	Calle.create(:id=>166, :barrio_id=>43, :nombre=>'ALAMEDA')
	Calle.create(:id=>167, :barrio_id=>43, :nombre=>'ALFONSINA STORNI')
	Calle.create(:id=>168, :barrio_id=>43, :nombre=>'ALTO PENCOSO')
	Calle.create(:id=>169, :barrio_id=>43, :nombre=>'AMERICA.')
	Calle.create(:id=>170, :barrio_id=>43, :nombre=>'ANCHORENA.')
	Calle.create(:id=>171, :barrio_id=>43, :nombre=>'ARTESANOS KOSLAYENSES')
	Calle.create(:id=>172, :barrio_id=>43, :nombre=>'AV. DEL VIENTO CHORRILLER')
	Calle.create(:id=>173, :barrio_id=>43, :nombre=>'AV. EJERCITO ARGENTINO')
	Calle.create(:id=>174, :barrio_id=>43, :nombre=>'AV. LAS CHACRAS')
	Calle.create(:id=>175, :barrio_id=>43, :nombre=>'BALET, ROGER')
	Calle.create(:id=>176, :barrio_id=>43, :nombre=>'CALLE PROYECTADA')
	Calle.create(:id=>177, :barrio_id=>43, :nombre=>'CALLEJON OJEDA')
	Calle.create(:id=>178, :barrio_id=>43, :nombre=>'CAMPAMENTO DE LAS CHACRAS')
	Calle.create(:id=>179, :barrio_id=>43, :nombre=>'CANTANTAL')
	Calle.create(:id=>180, :barrio_id=>43, :nombre=>'CHIPISCUY')
	Calle.create(:id=>181, :barrio_id=>43, :nombre=>'COMECHINGONES')
	Calle.create(:id=>182, :barrio_id=>43, :nombre=>'CONCARAN.')
	Calle.create(:id=>183, :barrio_id=>43, :nombre=>'COSTANERA SUR')
	Calle.create(:id=>184, :barrio_id=>43, :nombre=>'EL CALDEN.')
	Calle.create(:id=>185, :barrio_id=>43, :nombre=>'EL CHAÑAR')
	Calle.create(:id=>186, :barrio_id=>43, :nombre=>'FATIMA.')
	Calle.create(:id=>187, :barrio_id=>43, :nombre=>'FRAY M. ESQUIU')
	Calle.create(:id=>188, :barrio_id=>43, :nombre=>'GONZALEZ PEDRO H.')
	Calle.create(:id=>189, :barrio_id=>43, :nombre=>'HUARPES SUR')
	Calle.create(:id=>190, :barrio_id=>43, :nombre=>'HUARPES.')
	Calle.create(:id=>191, :barrio_id=>43, :nombre=>'JUSTO DARACT')
	Calle.create(:id=>192, :barrio_id=>43, :nombre=>'LAS HIGUERAS')
	Calle.create(:id=>193, :barrio_id=>43, :nombre=>'LOS DURAZNOS')
	Calle.create(:id=>194, :barrio_id=>43, :nombre=>'LOS PEJES')
	Calle.create(:id=>195, :barrio_id=>43, :nombre=>'LOS QUEBRACHOS.')
	Calle.create(:id=>196, :barrio_id=>43, :nombre=>'LOTEO FUNCIA')
	Calle.create(:id=>197, :barrio_id=>43, :nombre=>'MAESTROS PUNTANOS')
	Calle.create(:id=>198, :barrio_id=>43, :nombre=>'MALVINAS ARGENTINAS')
	Calle.create(:id=>199, :barrio_id=>43, :nombre=>'MANANTIAL.')
	Calle.create(:id=>200, :barrio_id=>43, :nombre=>'MARIA REINA DE LA PAZ')
	Calle.create(:id=>201, :barrio_id=>43, :nombre=>'MICHILINGUEZ')
	Calle.create(:id=>202, :barrio_id=>43, :nombre=>'MONTIEL')
	Calle.create(:id=>203, :barrio_id=>43, :nombre=>'NIÑAS DE AYOHUMA.')
	Calle.create(:id=>204, :barrio_id=>43, :nombre=>'NUESTRA SRA REINA DE LA PAZ')
	Calle.create(:id=>205, :barrio_id=>43, :nombre=>'PALABRA FINAL')
	Calle.create(:id=>206, :barrio_id=>43, :nombre=>'PANCANTA.')
	Calle.create(:id=>207, :barrio_id=>43, :nombre=>'PASAJE BERARDI')
	Calle.create(:id=>208, :barrio_id=>43, :nombre=>'PASAJE LAS MARGARITAS')
	Calle.create(:id=>209, :barrio_id=>43, :nombre=>'PASAJE ROCA')
	Calle.create(:id=>210, :barrio_id=>43, :nombre=>'PASAJE RODRIGUEZ')
	Calle.create(:id=>211, :barrio_id=>43, :nombre=>'PIEDRA BLANCA.')
	Calle.create(:id=>212, :barrio_id=>43, :nombre=>'PJE LAS MARGARITAS')
	Calle.create(:id=>213, :barrio_id=>43, :nombre=>'PJE. LOS HORNOS.')
	Calle.create(:id=>214, :barrio_id=>43, :nombre=>'PUESTA DEL SOL')
	Calle.create(:id=>215, :barrio_id=>43, :nombre=>'QUIROGA, LINDOR')
	Calle.create(:id=>216, :barrio_id=>43, :nombre=>'RANQUELES')
	Calle.create(:id=>217, :barrio_id=>43, :nombre=>'RIO DE LAS CARPAS')
	Calle.create(:id=>218, :barrio_id=>43, :nombre=>'RIO SECO')
	Calle.create(:id=>219, :barrio_id=>43, :nombre=>'RUTA 20')
	Calle.create(:id=>220, :barrio_id=>43, :nombre=>'RUTA 7')
	Calle.create(:id=>221, :barrio_id=>43, :nombre=>'SANCHEZ LAFUENTE, JUAN')
	Calle.create(:id=>222, :barrio_id=>43, :nombre=>'SAUCES DEL CHORRILLO')
	Calle.create(:id=>223, :barrio_id=>43, :nombre=>'TOESCA, ANACLETO')
	Calle.create(:id=>224, :barrio_id=>43, :nombre=>'TOMOLASTA')
	Calle.create(:id=>225, :barrio_id=>43, :nombre=>'VIRGEN DEL CARMEN')
	Calle.create(:id=>226, :barrio_id=>44, :nombre=>'1 DE MAYO')
	Calle.create(:id=>227, :barrio_id=>44, :nombre=>'18 DE FEBRERO')
	Calle.create(:id=>228, :barrio_id=>44, :nombre=>'20 DE NOVIEMBRE')
	Calle.create(:id=>229, :barrio_id=>44, :nombre=>'28 DE FEBRERO')
	Calle.create(:id=>230, :barrio_id=>44, :nombre=>'ADARO')
	Calle.create(:id=>231, :barrio_id=>44, :nombre=>'AGUADA DE LOS PADRES')
	Calle.create(:id=>232, :barrio_id=>44, :nombre=>'AGUADA DE PUEYRREDON')
	Calle.create(:id=>233, :barrio_id=>44, :nombre=>'AGUERO, ESTEBAN')
	Calle.create(:id=>234, :barrio_id=>44, :nombre=>'ALAMEDA')
	Calle.create(:id=>235, :barrio_id=>44, :nombre=>'ALFONSINA STORNI')
	Calle.create(:id=>236, :barrio_id=>44, :nombre=>'ALTO PENCOSO')
	Calle.create(:id=>237, :barrio_id=>44, :nombre=>'AMERICA.')
	Calle.create(:id=>238, :barrio_id=>44, :nombre=>'ANCHORENA.')
	Calle.create(:id=>239, :barrio_id=>44, :nombre=>'ARAUCANOS.')
	Calle.create(:id=>240, :barrio_id=>44, :nombre=>'ARTESANOS KOSLAYENSES')
	Calle.create(:id=>241, :barrio_id=>44, :nombre=>'AV EJERCITO ARGENTINO')
	Calle.create(:id=>242, :barrio_id=>44, :nombre=>'AV. CENTRAL LOS NOGALES')
	Calle.create(:id=>243, :barrio_id=>44, :nombre=>'AV. DEL VIENTO CHORRILLER')
	Calle.create(:id=>244, :barrio_id=>44, :nombre=>'AV. EJERCITO ARGENTINO')
	Calle.create(:id=>245, :barrio_id=>44, :nombre=>'AV. LAS CHACRAS')
	Calle.create(:id=>246, :barrio_id=>44, :nombre=>'AV. PRESIDENTE PERON')
	Calle.create(:id=>247, :barrio_id=>44, :nombre=>'B LOS VENADOS')
	Calle.create(:id=>248, :barrio_id=>44, :nombre=>'BALET, ROGER')
	Calle.create(:id=>249, :barrio_id=>44, :nombre=>'BERTIN JORGE S')
	Calle.create(:id=>250, :barrio_id=>44, :nombre=>'CACIQUE KOSLAY.')
	Calle.create(:id=>251, :barrio_id=>44, :nombre=>'CALLE PROYECTADA S N')
	Calle.create(:id=>252, :barrio_id=>44, :nombre=>'CALLEJON ROCA')
	Calle.create(:id=>253, :barrio_id=>44, :nombre=>'CAMPAMENTO DE LAS CHACRAS')
	Calle.create(:id=>254, :barrio_id=>44, :nombre=>'CANTANTAL')
	Calle.create(:id=>255, :barrio_id=>44, :nombre=>'CAÑADA HONDA')
	Calle.create(:id=>256, :barrio_id=>44, :nombre=>'CERRO DE LA CRUZ.')
	Calle.create(:id=>257, :barrio_id=>44, :nombre=>'CHIPISCUY')
	Calle.create(:id=>258, :barrio_id=>44, :nombre=>'CHORRILLO.')
	Calle.create(:id=>259, :barrio_id=>44, :nombre=>'COMECHINGONES')
	Calle.create(:id=>260, :barrio_id=>44, :nombre=>'CONCARAN.')
	Calle.create(:id=>261, :barrio_id=>44, :nombre=>'CONLARA')
	Calle.create(:id=>262, :barrio_id=>44, :nombre=>'COSTANERA SUR')
	Calle.create(:id=>263, :barrio_id=>44, :nombre=>'DR. A. RODRIGUEZ SAA')
	Calle.create(:id=>264, :barrio_id=>44, :nombre=>'DR. JUAN C. SAA.')
	Calle.create(:id=>265, :barrio_id=>44, :nombre=>'EL CALDEN.')
	Calle.create(:id=>266, :barrio_id=>44, :nombre=>'EL PINO')
	Calle.create(:id=>267, :barrio_id=>44, :nombre=>'ESQUIU, FRAY MAMERTO')
	Calle.create(:id=>268, :barrio_id=>44, :nombre=>'EX AGUADA DE PUEYRRE')
	Calle.create(:id=>269, :barrio_id=>44, :nombre=>'FATIMA')
	Calle.create(:id=>270, :barrio_id=>44, :nombre=>'FATIMA.')
	Calle.create(:id=>271, :barrio_id=>44, :nombre=>'FRAY M. ESQUIU')
	Calle.create(:id=>272, :barrio_id=>44, :nombre=>'FUNES, JUAN GILBERTO')
	Calle.create(:id=>273, :barrio_id=>44, :nombre=>'GOMEZ, ISLEÑO')
	Calle.create(:id=>274, :barrio_id=>44, :nombre=>'GONZALEZ PEDRO H.')
	Calle.create(:id=>275, :barrio_id=>44, :nombre=>'HEROES DE PTO.MADRYN')
	Calle.create(:id=>276, :barrio_id=>44, :nombre=>'HUARPES SUR')
	Calle.create(:id=>277, :barrio_id=>44, :nombre=>'HUARPES.')
	Calle.create(:id=>278, :barrio_id=>44, :nombre=>'ISLEÑO GOMEZ')
	Calle.create(:id=>279, :barrio_id=>44, :nombre=>'JOSE M ESTRADA')
	Calle.create(:id=>280, :barrio_id=>44, :nombre=>'JUANA KOSLAY')
	Calle.create(:id=>281, :barrio_id=>44, :nombre=>'LA ESCONDIDA')
	Calle.create(:id=>282, :barrio_id=>44, :nombre=>'LA PANCHA HERNANDEZ')
	Calle.create(:id=>283, :barrio_id=>44, :nombre=>'LAS CALANDRIAS')
	Calle.create(:id=>284, :barrio_id=>44, :nombre=>'LAS CHACRAS')
	Calle.create(:id=>285, :barrio_id=>44, :nombre=>'LAS HIGUERAS')
	Calle.create(:id=>286, :barrio_id=>44, :nombre=>'LOS DURAZNOS')
	Calle.create(:id=>287, :barrio_id=>44, :nombre=>'LOS ESPINILLOS')
	Calle.create(:id=>288, :barrio_id=>44, :nombre=>'LOS HORNOS')
	Calle.create(:id=>289, :barrio_id=>44, :nombre=>'LOS MOLLES')
	Calle.create(:id=>290, :barrio_id=>44, :nombre=>'LOS PEJES')
	Calle.create(:id=>291, :barrio_id=>44, :nombre=>'LOS QUEBRACHOS.')
	Calle.create(:id=>292, :barrio_id=>44, :nombre=>'LOS RANQUELES')
	Calle.create(:id=>293, :barrio_id=>44, :nombre=>'LOS RETAMOS.')
	Calle.create(:id=>294, :barrio_id=>44, :nombre=>'LOS SOCABONES')
	Calle.create(:id=>295, :barrio_id=>44, :nombre=>'LOS TALAS')
	Calle.create(:id=>296, :barrio_id=>44, :nombre=>'LOS ZORZALES.')
	Calle.create(:id=>297, :barrio_id=>44, :nombre=>'MAESTROS PUNTANOS')
	Calle.create(:id=>298, :barrio_id=>44, :nombre=>'MANANTIAL.')
	Calle.create(:id=>299, :barrio_id=>44, :nombre=>'MARIA REINA DE LA PAZ')
	Calle.create(:id=>300, :barrio_id=>44, :nombre=>'MICHILINGUEZ')
	Calle.create(:id=>301, :barrio_id=>44, :nombre=>'MONTIEL')
	Calle.create(:id=>302, :barrio_id=>44, :nombre=>'MTRO. GONZALEZ')
	Calle.create(:id=>303, :barrio_id=>44, :nombre=>'MULTITROCHA R.NAC.7-R.PROV.9')
	Calle.create(:id=>304, :barrio_id=>44, :nombre=>'NIÑAS DE AYOHUMA.')
	Calle.create(:id=>305, :barrio_id=>44, :nombre=>'NUESTRA SRA REINA DE LA PAZ')
	Calle.create(:id=>306, :barrio_id=>44, :nombre=>'PANCANTA.')
	Calle.create(:id=>307, :barrio_id=>44, :nombre=>'PARAISO ESCONDIDO')
	Calle.create(:id=>308, :barrio_id=>44, :nombre=>'PASAJE ROCA')
	Calle.create(:id=>309, :barrio_id=>44, :nombre=>'PASAJE RODRIGUEZ')
	Calle.create(:id=>310, :barrio_id=>44, :nombre=>'PIEDRA BLANCA.')
	Calle.create(:id=>311, :barrio_id=>44, :nombre=>'PJE. LOS HORNOS.')
	Calle.create(:id=>312, :barrio_id=>44, :nombre=>'PJE. MARIA  BERRUETA')
	Calle.create(:id=>313, :barrio_id=>44, :nombre=>'PJE. OJEDA JOSE')
	Calle.create(:id=>314, :barrio_id=>44, :nombre=>'PUESTA DEL SOL')
	Calle.create(:id=>315, :barrio_id=>44, :nombre=>'QUIROGA, LINDOR')
	Calle.create(:id=>316, :barrio_id=>44, :nombre=>'RANQUELES')
	Calle.create(:id=>317, :barrio_id=>44, :nombre=>'REGINO GARRO')
	Calle.create(:id=>318, :barrio_id=>44, :nombre=>'RIO DE LAS CARPAS')
	Calle.create(:id=>319, :barrio_id=>44, :nombre=>'RIO DE LAS CARPAS SUR')
	Calle.create(:id=>320, :barrio_id=>44, :nombre=>'RIO SECO')
	Calle.create(:id=>321, :barrio_id=>44, :nombre=>'RIO SOCOSCORA')
	Calle.create(:id=>322, :barrio_id=>44, :nombre=>'RODRÍGUEZ SAA ADOLFO DR')
	Calle.create(:id=>323, :barrio_id=>44, :nombre=>'RUTA   7 KM 781,5')
	Calle.create(:id=>324, :barrio_id=>44, :nombre=>'RUTA  18')
	Calle.create(:id=>325, :barrio_id=>44, :nombre=>'RUTA 148 KM  13.')
	Calle.create(:id=>326, :barrio_id=>44, :nombre=>'RUTA 20')
	Calle.create(:id=>327, :barrio_id=>44, :nombre=>'RUTA 7')
	Calle.create(:id=>328, :barrio_id=>44, :nombre=>'RUTA 7  KM 782')
	Calle.create(:id=>329, :barrio_id=>44, :nombre=>'SAN JOSE OBRERO')
	Calle.create(:id=>330, :barrio_id=>44, :nombre=>'SAN ROQUE')
	Calle.create(:id=>331, :barrio_id=>44, :nombre=>'SANCHEZ LAFUENTE, JUAN')
	Calle.create(:id=>332, :barrio_id=>44, :nombre=>'SANTA TERESA DE LOS ANDES')
	Calle.create(:id=>333, :barrio_id=>44, :nombre=>'SANTO DOMINGO')
	Calle.create(:id=>334, :barrio_id=>44, :nombre=>'SANTOS ORTIZ')
	Calle.create(:id=>335, :barrio_id=>44, :nombre=>'SAUCES DEL CHORRILLO')
	Calle.create(:id=>336, :barrio_id=>44, :nombre=>'TOESCA, ANACLETO')
	Calle.create(:id=>337, :barrio_id=>44, :nombre=>'TOMOLASTA')
	Calle.create(:id=>338, :barrio_id=>44, :nombre=>'URBANO J. NUÑEZ')
	Calle.create(:id=>339, :barrio_id=>44, :nombre=>'VELAZCO, PEDRO')
	Calle.create(:id=>340, :barrio_id=>44, :nombre=>'VICENTE VAZQUEZ')
	Calle.create(:id=>341, :barrio_id=>44, :nombre=>'VIDELA JOSE TORIBIO')
	Calle.create(:id=>342, :barrio_id=>44, :nombre=>'VIRGEN DEL CARMEN')
	Calle.create(:id=>343, :barrio_id=>45, :nombre=>'EDIFICIO 1')
	Calle.create(:id=>344, :barrio_id=>45, :nombre=>'EDIFICIO 10')
	Calle.create(:id=>345, :barrio_id=>45, :nombre=>'EDIFICIO 11')
	Calle.create(:id=>346, :barrio_id=>45, :nombre=>'EDIFICIO 12')
	Calle.create(:id=>347, :barrio_id=>45, :nombre=>'EDIFICIO 13')
	Calle.create(:id=>348, :barrio_id=>45, :nombre=>'EDIFICIO 14')
	Calle.create(:id=>349, :barrio_id=>45, :nombre=>'EDIFICIO 2')
	Calle.create(:id=>350, :barrio_id=>45, :nombre=>'EDIFICIO 3')
	Calle.create(:id=>351, :barrio_id=>45, :nombre=>'EDIFICIO 4')
	Calle.create(:id=>352, :barrio_id=>45, :nombre=>'EDIFICIO 5')
	Calle.create(:id=>353, :barrio_id=>45, :nombre=>'EDIFICIO 6')
	Calle.create(:id=>354, :barrio_id=>45, :nombre=>'EDIFICIO 7 (OROFINO)')
	Calle.create(:id=>355, :barrio_id=>45, :nombre=>'EDIFICIO 8')
	Calle.create(:id=>356, :barrio_id=>45, :nombre=>'EDIFICIO 9')
	Calle.create(:id=>357, :barrio_id=>46, :nombre=>'CAMINO EL ZAPALLAR')
	Calle.create(:id=>358, :barrio_id=>47, :nombre=>'ACCESO AL BARRIO')
	Calle.create(:id=>359, :barrio_id=>47, :nombre=>'CALLE 1')
	Calle.create(:id=>360, :barrio_id=>47, :nombre=>'LOBOS, E.')
	Calle.create(:id=>361, :barrio_id=>47, :nombre=>'LOS ¥ANDUES')
	Calle.create(:id=>362, :barrio_id=>48, :nombre=>'CAMINO EL ZAPALLAR')
	Calle.create(:id=>363, :barrio_id=>48, :nombre=>'CAMINO VECINAL')
	Calle.create(:id=>364, :barrio_id=>48, :nombre=>'J. W. GEZ')
	Calle.create(:id=>365, :barrio_id=>48, :nombre=>'RUTA 30')
	Calle.create(:id=>366, :barrio_id=>48, :nombre=>'RUTA 34')
	Calle.create(:id=>367, :barrio_id=>48, :nombre=>'SA 0865')
	Calle.create(:id=>368, :barrio_id=>49, :nombre=>'LA CUMBRE')
	Calle.create(:id=>369, :barrio_id=>49, :nombre=>'RUTA  7 KM 760')
	Calle.create(:id=>370, :barrio_id=>50, :nombre=>'LOTE')
	Calle.create(:id=>371, :barrio_id=>51, :nombre=>'LA PANCHA HERNANDEZ')
	Calle.create(:id=>372, :barrio_id=>52, :nombre=>'BLOCK A')
	Calle.create(:id=>373, :barrio_id=>52, :nombre=>'BLOCK B')
	Calle.create(:id=>374, :barrio_id=>52, :nombre=>'BLOCK C')
	Calle.create(:id=>375, :barrio_id=>52, :nombre=>'BLOCK D')
	Calle.create(:id=>376, :barrio_id=>52, :nombre=>'BLOCK E')
	Calle.create(:id=>377, :barrio_id=>52, :nombre=>'BLOCK F')
	Calle.create(:id=>378, :barrio_id=>52, :nombre=>'BLOCK G')
	Calle.create(:id=>379, :barrio_id=>52, :nombre=>'BLOCK H')
	Calle.create(:id=>380, :barrio_id=>52, :nombre=>'BLOCK I')
	Calle.create(:id=>381, :barrio_id=>52, :nombre=>'BLOCK J')
	Calle.create(:id=>382, :barrio_id=>52, :nombre=>'BLOCK K')
	Calle.create(:id=>383, :barrio_id=>52, :nombre=>'BLOCK L')
	Calle.create(:id=>384, :barrio_id=>52, :nombre=>'BLOCK M')
	Calle.create(:id=>385, :barrio_id=>52, :nombre=>'BLOCK N')
	Calle.create(:id=>386, :barrio_id=>52, :nombre=>'BOULEVARD PRINCIPAL')
	Calle.create(:id=>387, :barrio_id=>53, :nombre=>'BOULEVARD')
	Calle.create(:id=>388, :barrio_id=>54, :nombre=>'LOTE')
	Calle.create(:id=>389, :barrio_id=>55, :nombre=>'AV. EL PORTEZUELO')
	Calle.create(:id=>390, :barrio_id=>56, :nombre=>'LOTE')
	Calle.create(:id=>391, :barrio_id=>56, :nombre=>'MANZANA 35')
	Calle.create(:id=>392, :barrio_id=>56, :nombre=>'PARCELA')
	Calle.create(:id=>393, :barrio_id=>57, :nombre=>'PARCELA')
	Calle.create(:id=>394, :barrio_id=>58, :nombre=>'BLOCK 1')
	Calle.create(:id=>395, :barrio_id=>58, :nombre=>'BLOCK 2')
	Calle.create(:id=>396, :barrio_id=>59, :nombre=>'AV. EL PORTEZUELO')
	Calle.create(:id=>397, :barrio_id=>60, :nombre=>'PARCELA 1693')
	Calle.create(:id=>398, :barrio_id=>60, :nombre=>'PARCELA 1698')
	Calle.create(:id=>399, :barrio_id=>60, :nombre=>'PARCELA 1705')
	Calle.create(:id=>400, :barrio_id=>61, :nombre=>'LAS ROSAS')
	Calle.create(:id=>401, :barrio_id=>62, :nombre=>'LOTE')
	Calle.create(:id=>402, :barrio_id=>63, :nombre=>'ACCESO MONUMENTO')
	Calle.create(:id=>403, :barrio_id=>63, :nombre=>'AV. EL PORTEZUELO')
	Calle.create(:id=>404, :barrio_id=>63, :nombre=>'AV. LAS CHACRAS')
	Calle.create(:id=>405, :barrio_id=>63, :nombre=>'AV. PRESIDENTE PERON')
	Calle.create(:id=>406, :barrio_id=>63, :nombre=>'BUSTOS, BASILIO')
	Calle.create(:id=>407, :barrio_id=>63, :nombre=>'CAMINO AL MONUMENTO')
	Calle.create(:id=>408, :barrio_id=>63, :nombre=>'CAMINO TIEMPO COMPARTIDO')
	Calle.create(:id=>409, :barrio_id=>63, :nombre=>'CONTRIBUCION PATRIOTICA')
	Calle.create(:id=>410, :barrio_id=>63, :nombre=>'EL ALGARROBO')
	Calle.create(:id=>411, :barrio_id=>63, :nombre=>'EL CERRO')
	Calle.create(:id=>412, :barrio_id=>63, :nombre=>'EL JILGUERO')
	Calle.create(:id=>413, :barrio_id=>63, :nombre=>'EL PINO')
	Calle.create(:id=>414, :barrio_id=>63, :nombre=>'EX RUTA 18')
	Calle.create(:id=>415, :barrio_id=>63, :nombre=>'FRANCO, GREGORIO')
	Calle.create(:id=>416, :barrio_id=>63, :nombre=>'GUERRERO, INOCENCIO')
	Calle.create(:id=>417, :barrio_id=>63, :nombre=>'INST.UNIV.SEG.INTEGRAL')
	Calle.create(:id=>418, :barrio_id=>63, :nombre=>'LA MARQUEZA')
	Calle.create(:id=>419, :barrio_id=>63, :nombre=>'LA PANCHA HERNANDEZ')
	Calle.create(:id=>420, :barrio_id=>63, :nombre=>'LA RIOJA')
	Calle.create(:id=>421, :barrio_id=>63, :nombre=>'LAS ACACIAS')
	Calle.create(:id=>422, :barrio_id=>63, :nombre=>'LAS ARTES')
	Calle.create(:id=>423, :barrio_id=>63, :nombre=>'LAS CALANDRIAS')
	Calle.create(:id=>424, :barrio_id=>63, :nombre=>'LAS CHACRAS')
	Calle.create(:id=>425, :barrio_id=>63, :nombre=>'LAS GOLONDRINAS')
	Calle.create(:id=>426, :barrio_id=>63, :nombre=>'LAS ROSAS')
	Calle.create(:id=>427, :barrio_id=>63, :nombre=>'LAS TIJERETAS')
	Calle.create(:id=>428, :barrio_id=>63, :nombre=>'LAS TORCAZAS.')
	Calle.create(:id=>429, :barrio_id=>63, :nombre=>'LORENZO VARGAS')
	Calle.create(:id=>430, :barrio_id=>63, :nombre=>'LOS BENTEVEOS')
	Calle.create(:id=>431, :barrio_id=>63, :nombre=>'LOS HORNEROS')
	Calle.create(:id=>432, :barrio_id=>63, :nombre=>'LOS LEÑOS')
	Calle.create(:id=>433, :barrio_id=>63, :nombre=>'LOS LOPEZ')
	Calle.create(:id=>434, :barrio_id=>63, :nombre=>'LOS MANZANOS')
	Calle.create(:id=>435, :barrio_id=>63, :nombre=>'LOS PARAISOS')
	Calle.create(:id=>436, :barrio_id=>63, :nombre=>'LOS PICA HUESOS')
	Calle.create(:id=>437, :barrio_id=>63, :nombre=>'LOS PINOS')
	Calle.create(:id=>438, :barrio_id=>63, :nombre=>'LOS ROBLES')
	Calle.create(:id=>439, :barrio_id=>63, :nombre=>'LOS ZORZALES')
	Calle.create(:id=>440, :barrio_id=>63, :nombre=>'LUIS OSORIO')
	Calle.create(:id=>441, :barrio_id=>63, :nombre=>'LUNA, JUANARIO')
	Calle.create(:id=>442, :barrio_id=>63, :nombre=>'MARTIN PESCADOR')
	Calle.create(:id=>443, :barrio_id=>63, :nombre=>'PAJARO CARPINTERO')
	Calle.create(:id=>444, :barrio_id=>63, :nombre=>'PARAISO ESCONDIDO')
	Calle.create(:id=>445, :barrio_id=>63, :nombre=>'PARALELA A BVAR LAS ARTES')
	Calle.create(:id=>446, :barrio_id=>63, :nombre=>'PASAJE VANUCCI')
	Calle.create(:id=>447, :barrio_id=>63, :nombre=>'PASEO DEL CONDOR')
	Calle.create(:id=>448, :barrio_id=>63, :nombre=>'PAULINO SOSA')
	Calle.create(:id=>449, :barrio_id=>63, :nombre=>'PBRO CARLOS LOJOYA')
	Calle.create(:id=>450, :barrio_id=>63, :nombre=>'PJE SOSA PEDRO OESTE')
	Calle.create(:id=>451, :barrio_id=>63, :nombre=>'PJE. ESCONDIDO')
	Calle.create(:id=>452, :barrio_id=>63, :nombre=>'PROYECTADA N 12')
	Calle.create(:id=>453, :barrio_id=>63, :nombre=>'REY DEL BOSQUE')
	Calle.create(:id=>454, :barrio_id=>63, :nombre=>'RUISEÑOR')
	Calle.create(:id=>455, :barrio_id=>63, :nombre=>'RUM RUM')
	Calle.create(:id=>456, :barrio_id=>63, :nombre=>'RUTA  18 KM  15')
	Calle.create(:id=>457, :barrio_id=>63, :nombre=>'RUTA 18 KM 13')
	Calle.create(:id=>458, :barrio_id=>63, :nombre=>'RUTA 20')
	Calle.create(:id=>459, :barrio_id=>63, :nombre=>'SAN JUAN')
	Calle.create(:id=>460, :barrio_id=>63, :nombre=>'SAN LUIS')
	Calle.create(:id=>461, :barrio_id=>63, :nombre=>'SAN MIGUEL')
	Calle.create(:id=>462, :barrio_id=>63, :nombre=>'SANTA FE')
	Calle.create(:id=>463, :barrio_id=>64, :nombre=>'GUERRERO, INOCENCIO')
	Calle.create(:id=>464, :barrio_id=>65, :nombre=>'BLOCK A')
	Calle.create(:id=>465, :barrio_id=>65, :nombre=>'BLOCK B')
	Calle.create(:id=>466, :barrio_id=>66, :nombre=>'BLOCK A')
	Calle.create(:id=>467, :barrio_id=>66, :nombre=>'BLOCK B')
	Calle.create(:id=>468, :barrio_id=>66, :nombre=>'BLOCK C')
	Calle.create(:id=>469, :barrio_id=>67, :nombre=>'MANZANA A')
	Calle.create(:id=>470, :barrio_id=>67, :nombre=>'MANZANA B')
	Calle.create(:id=>471, :barrio_id=>67, :nombre=>'MANZANA C')
	Calle.create(:id=>472, :barrio_id=>67, :nombre=>'MANZANA D')
	Calle.create(:id=>473, :barrio_id=>67, :nombre=>'MANZANA E')
	Calle.create(:id=>474, :barrio_id=>67, :nombre=>'MANZANA F')
	Calle.create(:id=>475, :barrio_id=>67, :nombre=>'MANZANA G')
	Calle.create(:id=>476, :barrio_id=>67, :nombre=>'MANZANA H')
	Calle.create(:id=>477, :barrio_id=>67, :nombre=>'MANZANA I')
	Calle.create(:id=>478, :barrio_id=>67, :nombre=>'MANZANA J')
	Calle.create(:id=>479, :barrio_id=>67, :nombre=>'MANZANA K')
	Calle.create(:id=>480, :barrio_id=>67, :nombre=>'MANZANA L')
	Calle.create(:id=>481, :barrio_id=>67, :nombre=>'MANZANA M')
	Calle.create(:id=>482, :barrio_id=>67, :nombre=>'MANZANA N')
	Calle.create(:id=>483, :barrio_id=>68, :nombre=>'MANZANA 0')
	Calle.create(:id=>484, :barrio_id=>68, :nombre=>'MANZANA 2')
	Calle.create(:id=>485, :barrio_id=>68, :nombre=>'MANZANA 5')
	Calle.create(:id=>486, :barrio_id=>68, :nombre=>'MANZANA 6')
	Calle.create(:id=>487, :barrio_id=>68, :nombre=>'MANZANA 7')
	Calle.create(:id=>488, :barrio_id=>68, :nombre=>'MANZANA 9')
	Calle.create(:id=>489, :barrio_id=>69, :nombre=>'MANZANA A')
	Calle.create(:id=>490, :barrio_id=>69, :nombre=>'MANZANA C')
	Calle.create(:id=>491, :barrio_id=>70, :nombre=>'ENLACE CUCHI CORRAL RUTA 7')
	Calle.create(:id=>492, :barrio_id=>70, :nombre=>'LOS PUQUIOS')
	Calle.create(:id=>493, :barrio_id=>70, :nombre=>'MULTITROCHA LOS PUQUIOS')
	Calle.create(:id=>494, :barrio_id=>70, :nombre=>'PJE DOLORES ROSALES')
	Calle.create(:id=>495, :barrio_id=>70, :nombre=>'ROQUE DOMINGO DIAZ')
	Calle.create(:id=>496, :barrio_id=>71, :nombre=>'AV. LAS CHACRAS')
	Calle.create(:id=>497, :barrio_id=>72, :nombre=>'AUTOPISTA LOS PUQUIOS')
	Calle.create(:id=>498, :barrio_id=>72, :nombre=>'ENLACE CUCHI CORRAL RUTA 7')
	Calle.create(:id=>499, :barrio_id=>73, :nombre=>'CASA')
	Calle.create(:id=>500, :barrio_id=>74, :nombre=>'AV. LOS EUCALIPTUS')
	Calle.create(:id=>501, :barrio_id=>74, :nombre=>'LAS TIPAS')
	Calle.create(:id=>502, :barrio_id=>74, :nombre=>'MANZANA A')
	Calle.create(:id=>503, :barrio_id=>74, :nombre=>'MANZANA B')
	Calle.create(:id=>504, :barrio_id=>74, :nombre=>'MANZANA C')
	Calle.create(:id=>505, :barrio_id=>74, :nombre=>'MANZANA D')
	Calle.create(:id=>506, :barrio_id=>74, :nombre=>'MANZANA E')
	Calle.create(:id=>507, :barrio_id=>74, :nombre=>'MANZANA F')
	Calle.create(:id=>508, :barrio_id=>74, :nombre=>'MANZANA G')
	Calle.create(:id=>509, :barrio_id=>74, :nombre=>'MANZANA H')
	Calle.create(:id=>510, :barrio_id=>75, :nombre=>'MANZANA 11')
	Calle.create(:id=>511, :barrio_id=>75, :nombre=>'MANZANA 49')
	Calle.create(:id=>512, :barrio_id=>76, :nombre=>'CALLE PROYECTADA')
	Calle.create(:id=>513, :barrio_id=>76, :nombre=>'MANZANA 47')
	Calle.create(:id=>514, :barrio_id=>76, :nombre=>'MANZANA 48')
	Calle.create(:id=>515, :barrio_id=>76, :nombre=>'MANZANA 49')
	Calle.create(:id=>516, :barrio_id=>76, :nombre=>'MANZANA 50')
	Calle.create(:id=>517, :barrio_id=>76, :nombre=>'MANZANA 51')
	Calle.create(:id=>518, :barrio_id=>77, :nombre=>'MANZANA B (PARQUE INDUSTRIAL)')
	Calle.create(:id=>519, :barrio_id=>77, :nombre=>'MANZANA E')
	Calle.create(:id=>520, :barrio_id=>78, :nombre=>'26 DE JULIO')
	Calle.create(:id=>521, :barrio_id=>78, :nombre=>'AV SAN MARTIN')
	Calle.create(:id=>522, :barrio_id=>78, :nombre=>'AV. LOS EUCALIPTUS')
	Calle.create(:id=>523, :barrio_id=>78, :nombre=>'AV. PRESIDENTE PERON')
	Calle.create(:id=>524, :barrio_id=>78, :nombre=>'AV. SAN ROQUE')
	Calle.create(:id=>525, :barrio_id=>78, :nombre=>'CONTRIBUCION PATRIOTICA')
	Calle.create(:id=>526, :barrio_id=>78, :nombre=>'MANZANA B (PARQUE INDUSTRIAL)')
	Calle.create(:id=>527, :barrio_id=>78, :nombre=>'MULTITROCHA')
	Calle.create(:id=>528, :barrio_id=>78, :nombre=>'PASAJE SAN CAYETANO')
	Calle.create(:id=>529, :barrio_id=>78, :nombre=>'PASAJE SAN JOSE')
	Calle.create(:id=>530, :barrio_id=>78, :nombre=>'RIO SOCOSCORA')
	Calle.create(:id=>531, :barrio_id=>78, :nombre=>'RUTA 20')
	Calle.create(:id=>532, :barrio_id=>78, :nombre=>'SAN JOSE')
	Calle.create(:id=>533, :barrio_id=>78, :nombre=>'TINTITACO')

  end
end
